repos:
- repo: https://github.com/IvanArefkov/Artistic-chatbot.git
  # Ruff version.
  rev: v0.12.12
  hooks:
    # Run the linter.
    - id: ruff-check
      args: [ --fix ]
    # Run the formatter.
    - id: ruff-format